# Generated by Django 3.2 on 2022-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='f_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='l_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
