# Generated by Django 3.2 on 2022-04-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('surname', models.CharField(blank=True, max_length=15)),
                ('people', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('email', models.EmailField(max_length=100)),
                ('excerpt', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'failed'), (1, 'booked')], default=0)),
            ],
        ),
    ]
