# Generated by Django 3.2 on 2022-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0002_auto_20220419_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'booked')], default=0),
        ),
    ]
