# Generated by Django 3.2 on 2022-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0003_auto_20220421_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
