# Generated by Django 3.2 on 2022-04-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='start_time',
        ),
    ]
