# Generated by Django 3.2 on 2022-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0006_auto_20220424_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prefix',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BigIntegerField(choices=[(0, 'draft'), (1, 'booked')], default=0),
        ),
    ]
