# Generated by Django 3.2 on 2022-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0007_auto_20220424_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
