# Generated by Django 3.2 on 2022-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0008_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
