# Generated by Django 3.2 on 2022-04-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0009_auto_20220427_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=50)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_table', to='onepico.booking')),
            ],
        ),
    ]
