# Generated by Django 3.2 on 2022-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0010_auto_20220430_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
