# Generated by Django 3.2 on 2022-05-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0012_auto_20220503_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'booked')], default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'booked')], default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'booked')], default=0),
        ),
    ]
