# Generated by Django 3.2 on 2022-05-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0013_auto_20220503_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='px',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'rejected'), (3, 'expired')], default=0),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'rejected'), (3, 'expired')], default=0),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'rejected'), (3, 'expired')], default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.BigIntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'rejected'), (3, 'expired')], default=0),
        ),
    ]
