# Generated by Django 3.2 on 2022-05-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0015_remove_table_px'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
