# Generated by Django 3.2 on 2022-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0022_alter_booking_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='people',
            new_name='party_size',
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(choices=[('ES', '+34'), ('IR', '+353.'), ('EN', '+44')], max_length=15),
        ),
    ]
