# Generated by Django 3.2 on 2022-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0024_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prefix',
            field=models.BigIntegerField(choices=[('ES', '+34'), ('IR', '+353.'), ('EN', '+44')], default=353),
        ),
    ]
