# Generated by Django 3.2 on 2022-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0029_auto_20220906_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='prefix',
            field=models.BigIntegerField(blank=True, choices=[('+34', '+34'), ('+353', '+353'), ('+44', '+44')], default=353),
        ),
    ]
