# Generated by Django 3.2 on 2022-09-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepico', '0030_alter_booking_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='prefix',
            field=models.BigIntegerField(choices=[('+34', '+34'), ('+353', '+353'), ('+44', '+44')], default=353),
        ),
    ]
