# Generated by Django 3.2 on 2022-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_comment',
            field=models.TextField(),
        ),
    ]
